### PR TITLE
Implement relabeling functionality in the Loki logger.

### PR DESCRIPTION
**Pull request by ReneHollander**
This allows the user to control the labels on the entries sent to Loki, similar to how promtail allows it:
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#relabel_configs. This should grealy improve query performance by allowing the user to configure labels to filter their most relevant log entries.

There is no change to the default behavior of the logger with regards to the `identity` and `job` labels. But they can now be adjusted by the relabel-config as well.
Log entries can also be dropped if all labels are removed.

End to end tested:
image

### CODE REVIEW

**Review by dmachard — CHANGES_REQUESTED** [review]
Thank for this improvement

Can you fix the identity label please ?
It should be equal to the identity value of the DNStap message 

`labels.Label{Name: "identity", Value: o.name},`

by

`labels.Label{Name: "identity", Value: dm.DnsTap.Identity},`

**Comment by ReneHollander** [comment]
Good catch, fixed the identity label.

**Review by dmachard — CHANGES_REQUESTED** [review]
Thansk,  look good to me.

One more thing, can you make the linter happy ? You can add a new constant `DNSTAP_IDENTITY_TEST = "test_id"` in  dnsutils/constants.go 

```
Check failure on line 61 in loggers/logfile_test.go
GitHub Actions / linter

string `test_id` has 3 occurrences, make it a constant (goconst)

```

and update your test for example with

`dm.DnsTap.Identity = dnsutils.DNSTAP_IDENTITY_TEST`

**Comment by ReneHollander** [comment]
> One more thing, can you make the linter happy ?

Done.

**Review by dmachard — APPROVED** [review]

**Pull request merged**
