### PR TITLE
chg: [redispub] reading redis responses

### LINKED ISSUE #410: Logger: redispubsub - redis answers are not read.
Oversight from me: redis returns an integer when one `PUBLISH` data on a pubsub channel (https://redis.io/commands/publish/).
So `go-dnscollector` process's `Recv-Q` grows until its limits, then redis process's `Send-Q` grows to its limit and then `go-dnscollector` hangs.

PR incoming.

### PR DESCRIPTION
**Pull request by gallypette**
fix #410

### CODE REVIEW

**Comment by dmachard** [comment]
Responses from redis are discarded, it's can not be useful to read it in some cases ?
Otherwise, LGTM.
Thanks again

**Comment by gallypette** [comment]
The response in this case is the number of clients that consumed the message that was sent. It could be useful to some but I am more in a fire and forget situation regarding these messages.

**Comment by dmachard** [comment]
Ready to merge ?

**Comment by gallypette** [comment]
I think so.
My test instance's memory seems sane with this patch so #353 could be considered fixed.

**Comment by adulau** [comment]
We use it in production and it works as expected.

**Comment by dmachard** [comment]
Glad to hear that and thanks for your contributions.

Do you plan to share how  the DNS-collector is used in your side ? 
Usage in production may be useful for others :)

**Pull request merged**
