### PR TITLE
Added Clickhouse Logger

### PR DESCRIPTION
**Pull request by zunnurainbadar**
A new logger for Clickhouse has been added.
Files Changed:
=> dnsutils/config.go
=> doc/logger_clickhouse.md
=> loggers/clickhouse.go
=> loggers/clickhouse_test.go
=> dnscollector.go
=> README.md

### CODE REVIEW

**Comment by zunnurainbadar** [comment]
Yes. I will share the final schema in the final commit.

**Comment by johnhtodd** [comment]
This is very interesting - any news on a final version being available?

**Comment by zunnurainbadar** [comment]
Hello @johnhtodd, I've been quite occupied lately. Fortunately, I now have some time and plan to resume work on this starting this week. I'll be uploading the final version soon.

**Comment by dmachard** [comment]
I have resync your branch, I need your works.
Feel free to make a new PR to complete your works.

**Pull request merged**
