### PR TITLE
redesign config checker to support freeform keys

### LINKED ISSUE #676: Configuration checks breaks freeform keys
**Describe the bug**
The Scalyr logger has 2 configuration settings (`sessioninfo` and `attrs`) that can contain arbitrary key-value pairs. This is extra information sent alongside the data. This is configured as follows:

```yaml
    loggers:
    -   name: scalyr
        scalyrclient:
            apikey: XXXXX
            attrs:
                service: dnstap
                type: queries
            flush-interval: 10
            mode: flat-json
            sessioninfo:
                cloud_provider: Azure
                cloud_region: westeurope
```

When starting go-dnscollector, it errors (key name might differ, based on parsing order):

```
config error: unknown YAML key `cloud_region` in configuration
```

**To Reproduce**
Configure the scalyr logger as shown above, start go-dnscollector.

**Expected behavior**
go-dnscollector starts fine.

**Additional context**
 - Version 0.43.0 and commit 0267e3b47aa374b51df84ceacb61238258d3fdea

These fields in the config are a `map[string]string` and a `map[string]interface{}`. 

https://github.com/dmachard/go-dnscollector/blob/0267e3b47aa374b51df84ceacb61238258d3fdea/pkgconfig/loggers.go#L239-L240

Perhaps these field types should be ignored when converting the config to a map before checking it?

### PR DESCRIPTION
**Pull request by dmachard**
fix #676 

Individual function `IsValid` has been added to the following structs:
- Config
- ConfigGlobal
- ConfigCollectors
- ConfigLoggers
- ConfigMultiplexer
- ConfigPipelines
- ConfigTransformers

The config checker support freeform keys and the code is more easy to maintain!

### CODE REVIEW

**Comment by dmachard** [comment]
@pieterlexis-tomtom I would like to add you as reviewer but I cannot. Any feedback will be appreciated (if you can)

**Comment by pieterlexis-tomtom** [comment]
I'll have a look, but I must say I am not well-versed with `reflection`

**Comment by dmachard** [comment]
No worries, or just some tests will be great too.

**Comment by pieterlexis-tomtom** [comment]
This seems to work well on a few configs I tried :+1:. Good stuff!

**Comment by pieterlexis-tomtom** [comment]
If I can point to an improvement: You're reading the config file multiple times while loading (first for config, then checking), perhaps you should read it once and use the `byte[]` to create both the `map[string]interface{}` and `Config` struct? That ensures you're always working with the same data, should the file be changed underneath your feet.

**Comment by dmachard** [comment]
thanks, changed done!

**Pull request merged**
