### PR TITLE
Prometheus logger further performance improvements

### PR DESCRIPTION
**Pull request by kabenin**
type Prometheus now implements prometheus.Collector interface. This allows to remove most of prometheus.XXXVec fields, that were keeping duplicates of internal counters duplicates (the ones, updated in Record() function)

After this change, we do not need updating prometheus.XXXVec values every second. Instead, we generate Values for metrics on scraping (which runs Collect() function).

function ComputeMetrics renamed to ComputeEventsPerSecond, to beter reflect it's work.

added a few more test cases to cover more metrics and EPS updates.

### CODE REVIEW

**Comment by dmachard** [comment]
Thank for this great PR,
Some tests are failed because of the update of dnsutils.GetFakeDnsMessage() , can you take a look ?

**Comment by kabenin** [comment]
Updates to fix failing tests

**Comment by kabenin** [comment]
Looks like tests look fine now.

**Comment by kabenin** [comment]
Hi @dmachard! Thanks for sharing your load testing data. I'll definitely work on race conditions. Hopefully, that will not make it slower compared to PR #325.
If you could share your load testing setting, I would happy to test it on my side before submitting results.

Thanks!

**Comment by dmachard** [comment]
My setup is basic: ns1labs/flame ----> dnsdist --protobuf--> dnscollector 

**My dnsdist config (just a extract)**

```lua
-- copy the traffic 4 time to make stress test more high
rl1 = newRemoteLogger("192.168.1.17:6000")
rl2 = newRemoteLogger("192.168.1.17:6000")
rl3 = newRemoteLogger("192.168.1.17:6001")
rl4 = newRemoteLogger("192.168.1.17:6001")

addAction(AllRule(),RemoteLogAction(rl1, nil, {serverID="dnsdist1"}))
addResponseAction(AllRule(),RemoteLogResponseAction(rl1, nil, true, {serverID="dnsdist1"}))
addCacheHitResponseAction(AllRule(), RemoteLogResponseAction(rl1, nil, true, {serverID="dnsdist1"}))

addAction(AllRule(),RemoteLogAction(rl12, nil, {serverID="dnsdist2"}))
addResponseAction(AllRule(),RemoteLogResponseAction(rl2, nil, true, {serverID="dnsdist2"}))
addCacheHitResponseAction(AllRule(), RemoteLogResponseAction(rl2, nil, true, {serverID="dnsdist2"}))

addAction(AllRule(),RemoteLogAction(rl3, nil, {serverID="dnsdist3"}))
addResponseAction(AllRule(),RemoteLogResponseAction(rl3, nil, true, {serverID="dnsdist3"}))
addCacheHitResponseAction(AllRule(), RemoteLogResponseAction(rl3, nil, true, {serverID="dnsdist3"}))

addAction(AllRule(),RemoteLogAction(rl4, nil, {serverID="dnsdist4"}))
addResponseAction(AllRule(),RemoteLogResponseAction(rl4, nil, true, {serverID="dnsdist4"}))
addCacheHitResponseAction(AllRule(), RemoteLogResponseAction(rl4, nil, true, {serverID="dnsdist4"}))


-- spoof test.com to keep traffic local
addAction(AndRule({RegexRule(".*\\.test\\.com"), OrRule({QTypeRule(DNSQType.A),QTypeRule(DNSQType.AAAA) })  }), SpoofAction({"192.0.2.2", "2001:db8::3:1"}))
addAction(AndRule({RegexRule(".*\\.test\\.com"), QTypeRule(DNSQType.CNAME)  }), SpoofCNAMEAction("aaa.com", {}))
addAction(AndRule({RegexRule(".*\\.test\\.com"), QTypeRule(DNSQType.TXT)  }), SpoofRawAction({"\003aaa\004bbbb", "\003ccc"}) )
addAction(AndRule({RegexRule(".*\\.test\\.com"), QTypeRule(DNSQType.MX)  }), SpoofRawAction({"\000\010\004smtp\006google\003com\000"}) )
addAction(AndRule({RegexRule(".*\\.test\\.com"), QTypeRule(DNSQType.NS)  }), SpoofRawAction({"\003ns\049\006google\003com\000"}) )
addAction(AndRule({RegexRule(".*\\.test\\.com"), QTypeRule(DNSQType.SOA)  }), SpoofRawAction({"\003ns\049\006google\003com\000\009dns\045admin\006google\003com\000\031Eb\020\000\000\003\132\000\000\003\132\000\000\007\008\000\000\000\060"}) )
```

**dnscollector config:**

```
multiplexer:
  collectors:
    - name: tap
      powerdns:
        listen-ip: 0.0.0.0
        listen-port: 6000
    - name: tap2
      powerdns:
        listen-ip: 0.0.0.0
        listen-port: 6001
  loggers:
    - name: prom
      prometheus:
        listen-ip: 0.0.0.0
        listen-port: 8081
        basic-auth-enable: false

  routes:
    - from: [ tap, tap2 ]
      to: [ prom ]
```

**dns traffic generator**

`docker run  ns1labs/flame -p 53 -Q 15000 <yourdnsdistip> -g randomlabel lblsize=20 lblcount=10 count=100000`

**Comment by kabenin** [comment]
Hi @dmachard , thanks a lot for sharing your load testing setup!
With the latest updates it runs OK under the load along with 100 qps 'scrapes'.

**Comment by dmachard** [comment]
I make some new tests and the following race conditions occurred

```
WARNING: DATA RACE
Write at 0x00c0004226e0 by goroutine 37:
  github.com/dmachard/go-dnscollector/loggers.(*Prometheus).ComputeEventsPerSecond()
      /home/denis/Lab/github.com/go-dns-collector/loggers/prometheus.go:950 +0x7da
  github.com/dmachard/go-dnscollector/loggers.(*Prometheus).Process()
      /home/denis/Lab/github.com/go-dns-collector/loggers/prometheus.go:1086 +0x2ca
  github.com/dmachard/go-dnscollector/loggers.(*Prometheus).Run.func2()
      /home/denis/Lab/github.com/go-dns-collector/loggers/prometheus.go:1033 +0x39

Previous read at 0x00c0004226e0 by goroutine 222:
  github.com/dmachard/go-dnscollector/loggers.(*Prometheus).Collect()
      /home/denis/Lab/github.com/go-dns-collector/loggers/prometheus.go:788 +0x22e
  github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
      /home/denis/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/registry.go:455 +0x145
```

----

```
WARNING: DATA RACE
Read at 0x00c000002580 by goroutine 494:
  github.com/dmachard/go-dnscollector/loggers.(*Prometheus).Collect()
      /home/denis/Lab/github.com/go-dns-collector/loggers/prometheus.go:788 +0x22e
  github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
      /home/denis/go/pkg/mod/github.com/prometheus/client_golang@v1.15.1/prometheus/registry.go:455 +0x145

Previous write at 0x00c000002580 by goroutine 37:
  github.com/dmachard/go-dnscollector/loggers.(*Prometheus).ComputeEventsPerSecond()
      /home/denis/Lab/github.com/go-dns-collector/loggers/prometheus.go:950 +0x7da
  github.com/dmachard/go-dnscollector/loggers.(*Prometheus).Process()
      /home/denis/Lab/github.com/go-dns-collector/loggers/prometheus.go:1086 +0x2ca
  github.com/dmachard/go-dnscollector/loggers.(*Prometheus).Run.func2()
      /home/denis/Lab/github.com/go-dns-collector/loggers/prometheus.go:1033 +0x39

```

**Comment by kabenin** [comment]
Hi @dmachard!
Thank you for finding yet another race condition! I reproduced it. Fixed and does not show up anymore with -race.

**Comment by dmachard** [comment]
> Hi @dmachard! Thank you for finding yet another race condition! I reproduced it. Fixed and does not show up anymore with -race.

Thanks for the fix,
I will take a look in next weeks, I am missing  some time right now.

**Comment by kabenin** [comment]
Hi @dmachard , no rush at all! It is quite a change, and I do appreciate your thoughtful and cautious approach!

I'm currently working on another change, on top of this one. Currently, the 'anchor' label for all metrics is the stream_id. However, in our setup it is very important to have NetworkInfo.QueryIp as a label. I'm trying to create a configurable labeling, that, I hope, others may benefit from too. And I keep the performance in mind too. I hope you will consider that PR too.

Is it something you want to see in this PR, or as a separate one later on? 

Thanks!

**Comment by dmachard** [comment]
> I'm currently working on another change, on top of this one. Currently, the 'anchor' label for all metrics is the stream_id. However, in our setup it is very important to have NetworkInfo.QueryIp as a label. I'm trying to create a configurable labeling, that, I hope, others may benefit from too. And I keep the performance in mind too. I hope you will consider that PR too.
> 
> Is it something you want to see in this PR, or as a separate one later on?

As a separate PR, the release notes will be more clear.
Thanks a lot for your contributions

**Pull request merged**
