### PR TITLE
first shot for pipelling support 

### PR DESCRIPTION
**Pull request by dmachard**
@johnhtodd

This PR is a draft to validate the concept of pipelines in configuration.

- [x] introduce pippeline mode
- [x] new dnsmessage collector 
- [x] add regex support with flexible matching mode
- [x] new atags transform to validate the concept
- [x] support list in matching mode
- [x] support regex from external source (local file, remote one)
- [x] modify routes definition to be more generic
- [x] support routing on loggers and collector in a generic way
- [x] check pipeline config
- [x] The ability to entirely delete client IP addresses
- [x] The ability to limit infinite memory consumption or prometheus logger

This codebase will be the minimum to implement future versions.

New model of config:

```
pipelines:
  - name: main-input
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      default: [ filter ]

  - name: filter
    dnsmessage:
      matching:
        include:
          dns.qname: "^.*\\.google\\.com$"
    transforms:
      atags:
        tags: [ "google"]
    routing-policy:
      dropped: [ outputfile ]
      default: [ console ]

  - name: console
    stdout:
      mode: text

  - name: outputfile
    logfile:
      file-path:  "/tmp/dnstap.log"
      max-size: 1000
      max-files: 10
      mode: flat-json
```

### CODE REVIEW

**Comment by johnhtodd** [comment]
This seems to be working with no problems - I've put a few tens of millions of queries through it so far.  Testing has not been exhaustive, but other than the Prometheus bug (unrelated to this pipeline support) I'd say it's going well.

**Comment by johnhtodd** [comment]
Well, perhaps I was a bit premature in my comment.  I tried adding a dnstap output, and that doesn't seem to quite work:

```
  - name: godnsconnector-next
    dnstap:
      remote-address: 127.0.0.1
      remote-port: 59311

  - name: apple-txt
    dnsmessage:
      matching:
        include:
          dns.qtype: "TXT"
          dns.qname: "^*.apple.com$"
      policy: "drop-unmatched"
    transforms:
      atags:
        tags: [ "TXT:apple" ]
    routes: [ outputfile,godnsconnector-next ]

```

Adding those lines causes this error:

. . . 
INFO: 2023/12/15 22:26:27.808298 [tag-queries] collector=dnsmessage - enabled
panic: main - routing error: stage godnscollector-next doest not exist

goroutine 1 [running]:
main.InitPipelines(0xc000436840?, 0x13ba7b6?, 0xc000415300, 0x0?)
	/home/jtodd/go-dnscollector/go-dnscollector-pipeline-branch/go-dnscollector/pipeline.go:156 +0x1474
main.main()
	/home/jtodd/go-dnscollector/go-dnscollector-pipeline-branch/go-dnscollector/dnscollector.go:114 +0x508
root@ub20template:/home/jtodd/go-dnscollector/go-dnscollector-pipeline-branch/go-dnscollector#

**Comment by dmachard** [comment]
> Well, perhaps I was a bit premature in my comment. I tried adding a dnstap output, and that doesn't seem to quite work:
> 

The panic error should only occur during routing initialization. If a route is missing in the configuration, the application will be stopped.

After copying and pasting your configuration on my end, it's working fine without any panics. Can you confirm if you have this log on startup?

`INFO: 2023/12/17 10:48:47.415533 [godnsconnector-next] logger=dnstap - running in background...`

I will add more log messages to show the routing initialization process.

**Comment by johnhtodd** [comment]
Thanks - this was a typo on my part during testing.  Works as expected!

**Comment by dmachard** [comment]
yaml model improved with latest commit
with include/exclude section and more

```yaml
  - name: apple-txt
    dnsmessage:
      matching:
        include:
          dns.opcode: 0
          dns.length:
            greater-than: 50
          dns.qname:
            file-list: "./testsdata/filtering_keep_domains_regex.txt"
            file-kind: "domain_list"
        exclude:
          dns.qtype: [ "TXT", "MX" ]
          dns.qname:
            - ".*\\.github\\.com$"
            - "^www\\.google\\.com$"
      policy: "drop-unmatched"
    transforms:
      atags:
        tags: [ "TXT:apple", "TXT:google" ]
    routes: [ outputfile, console ]
```

**Comment by dmachard** [comment]
The new syntax to use:

```yaml
  - name: apple-txt
    dnsmessage:
      matching:
        include:
          dns.opcode: 0
          dns.length:
            greater-than: 50
          dns.qname:
            match-source: "file://./testsdata/filtering_keep_domains_regex.txt"
            source-kind: "regexp_list"
          dnstap.operation:
            match-source: "http://127.0.0.1/operation.txt"
            source-kind: "string_list"
        exclude:
          dns.qtype: [ "TXT", "MX" ]
          dns.qname:
            - ".*\\.github\\.com$"
            - "^www\\.google\\.com$"
      policy: "drop-unmatched"
    transforms:
      atags:
        tags: [ "TXT:apple", "TXT:google" ]
    routes: [ outputfile, console ]
```

**Comment by dmachard** [comment]
@johnhtodd 

The matching functionality has been extended to support any value in a list, such as dns.resource-records or atags.tags.

For example, to match specific answers only with a TTL greater than 300 and RDATA equal to a list of IPs.

```yaml
include:
  dns.resource-records.an.*.ttl:
    greater-than: 300
  dns.resource-records.an.*.rdata:
    - "^142\\.250\\.185\\.(196|132)$"
    - "^143\\.251\\.185\\.(196|132)$"
```

Second example to match a tag at position 0

```yaml
include:
  atags.tags.0: "TXT:apple"
```

**Comment by johnhtodd** [comment]
fantastic - will also try this tomorrow if I can before leaving for family travel.  This is looking very promising!

**Comment by dmachard** [comment]
New syntax for routing definition between stanza /!\ https://github.com/dmachard/go-dnscollector/issues/521

The `default` key  is used to configure where to send all matched/accepted dns messages.
And the `dropped`  key can be used to send unmached packets to another stanza in the config.

```
    routing-policy:
      dropped: [ outputfile ]
      default: [ console ]
```

**Pull request merged**
