### PR TITLE
Add more linters to golangci-lint

### PR DESCRIPTION
**Pull request by pieterlexis-tomtom**
This PR adds the following linters and fixes the code for said linters:

- govet
- goimports
- gosimple
- ineffassign
- stylecheck
- gocritic

### CODE REVIEW

**Comment by pieterlexis-tomtom** [comment]
The gocritic commit contains actual code changes. I can recommend reviewing that commit properly.

**Comment by dmachard** [comment]
If you're OK with it, I'll review this PR as first for v0.39.0
The v0.38.0 release is planned for next week.

**Comment by pieterlexis-tomtom** [comment]
No rush, just remember the conflicts will pile up :)

**Comment by dmachard** [comment]
Hi, the release v0.38.0 is out :) Can you resync your branch ? 
Thanks!

**Comment by pieterlexis-tomtom** [comment]
> Hi, the release v0.38.0 is out :) Could you please resynchronize your branch? Thanks!

Done, I hope I didn't mess things up :)

**Comment by pieterlexis-tomtom** [comment]
> The gocritic commit contains actual code changes. I can recommend reviewing that commit properly.

This comment is still relevant

**Review by dmachard — APPROVED** [review]

**Pull request merged**
