### PR TITLE
elasticsearch logger: change op_type to create to allow sending to Data Streams

### PR DESCRIPTION
**Pull request by ruffy91**
Since 0.35 indexing to elasticsearch does no longer work if the destination is a Data Stream.
This is because Data Streams only allow "create" (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)

This pull request changes the "index" to a "create" op_type which allows sending logs to a Data Stream again. 
"index" should not be needed as we never update existing documents.

### CODE REVIEW

**Comment by dmachard** [comment]
@arvchristos can you take a look  to this PR ? any remarks ?

**Comment by arvchristos** [comment]
The PR is totally on point. In the future, we need to have some integration tests to catch issues like this one (I did not consider data streams when I implemented the bulk approach). I need to think how to best do integration testing for the Opensearch/Elasticsearch outputs but this is definitely a contribution in the right direction.

**Comment by dmachard** [comment]
Thank for this quick feedback :)

@Fabian testunit need to be updated, CI raised the following error:

```
    elasticsearch_test.go:81: 
        	Error Trace:	/home/runner/work/go-dnscollector/go-dnscollector/loggers/elasticsearch_test.go:81
        	Error:      	Not equal: 
        	            	expected: map[string]interface {}(map[string]interface {}{})
        	            	actual  : <nil>(<nil>)
        	Test:       	Test_ElasticSearchClient/flat-json
 
```

**Comment by ruffy91** [comment]
I did not run the tests locally because it immediately worked for me after compiling. Now the test is changed too and passes.

**Comment by dmachard** [comment]
LGTM
thanks

**Pull request merged**
